### ISSUE TITLE
Account information duplicated

### ISSUE THREAD

**Issue by ed-davies** [kensanata/mastodon-backup#3]
The output is unnecessarily verbose as the account information is duplicated on each status.

**Comment by kensanata** [comment]
The benefit, on the other hand, is that it matches [what the API docs say](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#status) and [what the Mastodon.py library docs say](https://mastodonpy.readthedocs.io/en/latest/index.html?highlight=verify#return-values) so right now I feel inclined to not do anything about this. If you are worried about the file size, maybe we can simply gzip the output? Or if memory is a concern of yours, we could save the JSON file as we're reading pages instead of slurping it all in one go.
For now, I feel like closing this with WONTFIX unless there are some considerations I missed?

**Comment by ed-davies** [comment]
The benefit I was thinking of was simply readability.

However, for the reasons you mention it's probably not a good idea. Also, if somebody relies in code on the account being up at the top level (as I suggested in a forked repo) then that would create a trap if for any reason the accounts didn't all match and so were left on the status.

So I'll withdraw this suggestion.
